version: '3.8'
services:
    apachephp:
        container_name: apachephp
        image: webdevops/php-apache-dev:8.1
        working_dir: /app
        environment:
            docker: "true"
        links:
            - smtp4dev:smtp4dev
        ports:
            - 3005:80
            - 443:443
            # - 8080:8080
            # - 8080:80
        volumes:
            - .:/app
            - ./.container/logs:/var/www/logs
            # - .docker/php.ini:/opt/bitnami/php/lib/php.ini
            # - .docker/php.ini:/usr/local/etc/php/php.ini
        restart: always


    smtp4dev:
        # container_name: smtp4dev
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            # Change the number before : to the port the web interface should be accessible on
            - 5000:80
            # Change the number before : to the port the SMTP server should be accessible on
            - 25:25
            # Change the number before : to the port the IMAP server should be accessible on
            - 143:143
        volumes:
            # This is where smtp4dev stores the database..
            - ./.container/smtp4dev:/smtp4dev
        environment:
            # Uncomment to customise these settings

            #Specifies the virtual path from web server root where SMTP4DEV web interface will be hosted. e.g. "/" or "/smtp4dev"
            #- ServerOptions__BasePath=/smtp4dev

            #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
            - ServerOptions__HostName=smtp4dev
